### ISSUE TITLE
Release for version with Python 3.9 annotation bugfix?

### ISSUE THREAD

**Issue by warrickball** [MIST-Experiment/iricore#1]
I recently ran into a type hinting error when installing `iricore>=1.7.0` with Python 3.9. I was going to implement the appropriate fix (a missing `from __future__ import annotations` in `raytracing.py`) when I found that you've already implemented the fix in 167ff816ba78093afbd10912a546be743d4c3221.

Could you make a release (1.8.1?) so that this is available to install via pip?

**Comment by vbidula** [comment]
Hi @warrickball, thanks for letting me know. I pushed the 1.8.1 to PyPI (that also includes other improvements that I forgot to publish). It still has some known compilation issues on MacOS that will be fixed soon in 1.8.2, but since the mentioned problem has been addressed, I am closing the issue.
